grooves-api/src/main/groovy/com/github/rahulsom/grooves/api/EventsDsl.groovy
grooves-api/src/main/groovy/com/github/rahulsom/grooves/api/QueryUtil.groovy
grooves-api/src/main/groovy/com/github/rahulsom/grooves/api/Snapshot.groovy
grooves-api/src/test/resources/missing/MissingEvents.groovy
grooves-api/src/test/resources/valid/ValidES.groovy
grooves-example-grails-mongo/grails-app/controllers/grooves/grails/mongo/PatientController.groovy
grooves-example-grails-mongo/grails-app/domain/grooves/grails/mongo/PatientAccount.groovy
grooves-example-grails-mongo/grails-app/domain/grooves/grails/mongo/PatientHealth.groovy
grooves-example-grails-mongo/grails-app/i18n/messages.properties
grooves-example-grails-mongo/grails-app/init/grooves/example/grails/mongo/BootStrap.groovy
grooves-example-grails-rdbms/grails-app/controllers/grooves/grails/rdbms/PatientController.groovy
grooves-example-grails-rdbms/grails-app/domain/grooves/grails/rdbms/PatientAccount.groovy
grooves-example-grails-rdbms/grails-app/domain/grooves/grails/rdbms/PatientHealth.groovy
grooves-example-grails-rdbms/grails-app/domain/grooves/grails/rdbms/Procedure.groovy
grooves-example-grails-rdbms/grails-app/i18n/messages.properties
grooves-example-grails-rdbms/grails-app/init/grooves/example/grails/rdbms/BootStrap.groovy
grooves-example-grails-rdbms/src/main/groovy/grooves/grails/rdbms/PatientHealthQuery.groovy
grooves-example-springboot-jpa/src/main/groovy/grooves/boot/jpa/BootStrap.groovy
grooves-example-springboot-jpa/src/main/groovy/grooves/boot/jpa/controllers/PatientController.groovy
grooves-example-springboot-jpa/src/main/groovy/grooves/boot/jpa/domain/PatientAccount.groovy
grooves-example-springboot-jpa/src/main/groovy/grooves/boot/jpa/domain/PatientHealth.groovy
grooves-example-springboot-jpa/src/main/groovy/grooves/boot/jpa/domain/Procedure.groovy
grooves-example-springboot-jpa/src/main/groovy/grooves/boot/jpa/queries/PatientAccountQuery.groovy
grooves-example-springboot-jpa/src/main/groovy/grooves/boot/jpa/queries/PatientHealthQuery.groovy
grooves-example-springboot-jpa/src/main/groovy/grooves/boot/jpa/repositories/PatientAccountRepository.groovy
grooves-example-springboot-jpa/src/main/groovy/grooves/boot/jpa/repositories/PatientEventRepository.groovy
grooves-example-springboot-jpa/src/main/groovy/grooves/boot/jpa/repositories/PatientHealthRepository.groovy
grooves-example-test/src/main/groovy/com/github/rahulsom/grooves/test/AbstractPatientSpec.groovy
grooves-grails/src/main/groovy/com/github/rahulsom/grooves/grails/GormQueryUtil.groovy

This allows having temporal snapshots in addition to versioned snapshots.

Add date support

---

buildSrc/build.gradle
buildSrc/src/main/groovy/com/github/rahulsom/grooves/asciidoctor/Aggregate.groovy
buildSrc/src/main/groovy/com/github/rahulsom/grooves/asciidoctor/Constants.groovy
buildSrc/src/main/groovy/com/github/rahulsom/grooves/asciidoctor/Event.groovy
buildSrc/src/main/groovy/com/github/rahulsom/grooves/asciidoctor/EventType.groovy
buildSrc/src/main/groovy/com/github/rahulsom/grooves/asciidoctor/EventsBlock.groovy
buildSrc/src/main/groovy/com/github/rahulsom/grooves/asciidoctor/GroovesExtensionRegistry.groovy
buildSrc/src/main/groovy/com/github/rahulsom/grooves/asciidoctor/SvgBuilder.groovy
grooves-api/build.gradle
grooves-api/src/docs/asciidoc/index.adoc

This adds support to explaining how aggregates and events line up.

Improve documentation

---

examples/grails/rdbms/grails-app/init/grooves/example/grails/rdbms/BootStrap.groovy
examples/grails/rdbms_mongo/grails-app/init/grooves/example/grails/mongo/BootStrap.groovy
examples/grails/restserver/grails-app/init/restserver/BootStrap.groovy
examples/grails/rxmongo/grails-app/init/rxmongo/BootStrap.groovy
examples/javaee/src/main/java/grooves/example/javaee/BootStrap.java
examples/springboot/jpa/src/main/groovy/grooves/boot/jpa/BootStrap.groovy
examples/springboot/kotlin/src/main/kotlin/grooves/boot/kotlin/BootStrap.kt
grooves-example-test/src/main/groovy/com/github/rahulsom/grooves/test/AbstractPatientSpec.groovy

Freddie Mercury is a better fit than George Harrison was.

Sync test names with documentation

---

examples/grails/rdbms/grails-app/init/grooves/example/grails/rdbms/BootStrap.groovy
examples/grails/rdbms_mongo/grails-app/init/grooves/example/grails/mongo/BootStrap.groovy
examples/grails/restserver/grails-app/init/restserver/BootStrap.groovy
examples/grails/rxmongo/grails-app/init/rxmongo/BootStrap.groovy
examples/javaee/src/main/java/grooves/example/javaee/BootStrap.java
examples/springboot/jpa/src/main/groovy/grooves/boot/jpa/BootStrap.groovy
examples/springboot/kotlin/src/main/kotlin/grooves/boot/kotlin/BootStrap.kt

There was one place that this was left out

Replace George Harrison with Freddie Mercury

---

examples/grails/rdbms/grails-app/domain/grooves/grails/rdbms/PatientEvent.groovy
examples/grails/rdbms/grails-app/init/grooves/example/grails/rdbms/BootStrap.groovy
examples/grails/rdbms_mongo/grails-app/domain/grooves/grails/mongo/DoctorEvent.groovy
examples/grails/rdbms_mongo/grails-app/domain/grooves/grails/mongo/PatientEvent.groovy
examples/grails/rdbms_mongo/grails-app/domain/grooves/grails/mongo/ZipcodeEvent.groovy
examples/grails/rdbms_mongo/grails-app/init/grooves/example/grails/mongo/BootStrap.groovy
examples/grails/restserver/grails-app/init/restserver/BootStrap.groovy
examples/grails/rxmongo/grails-app/domain/rxmongo/PatientEvent.groovy
examples/grails/rxmongo/grails-app/init/rxmongo/BootStrap.groovy
examples/grails/rxrest/grails-app/domain/grooves/example/rxrest/PatientEvent.groovy
examples/javaee/src/main/java/grooves/example/javaee/BootStrap.java
examples/javaee/src/main/java/grooves/example/javaee/domain/PatientCreated.java
examples/javaee/src/main/java/grooves/example/javaee/domain/PatientDeprecatedBy.java
examples/javaee/src/main/java/grooves/example/javaee/domain/PatientDeprecates.java
examples/javaee/src/main/java/grooves/example/javaee/domain/PatientEvent.java
examples/javaee/src/main/java/grooves/example/javaee/domain/PatientEventReverted.java
examples/javaee/src/main/java/grooves/example/javaee/domain/PaymentMade.java
examples/javaee/src/main/java/grooves/example/javaee/domain/ProcedurePerformed.java
examples/springboot/jpa/src/main/groovy/grooves/boot/jpa/BootStrap.groovy
examples/springboot/jpa/src/main/groovy/grooves/boot/jpa/domain/PatientEvent.groovy
examples/springboot/kotlin/src/main/kotlin/grooves/boot/kotlin/BootStrap.kt
examples/springboot/kotlin/src/main/kotlin/grooves/boot/kotlin/domain/PatientEvent.kt
grooves-api/src/main/groovy/com/github/rahulsom/grooves/api/EventsDsl.java
grooves-api/src/main/groovy/com/github/rahulsom/grooves/api/OnSpec.java
grooves-groovy/src/main/groovy/com/github/rahulsom/grooves/groovy/GroovyEventsDsl.java
grooves-groovy/src/test/resources/domains.groovy
grooves-java/src/test/resources/domains/Transaction.java
grooves-types/src/main/kotlin/com/github/rahulsom/grooves/api/events/BaseEvent.kt

Remove createdBy and getAudit

---

CHANGELOG.adoc
examples/grails/rdbms/grails-app/controllers/grooves/grails/rdbms/PatientController.groovy
examples/grails/rdbms_mongo/grails-app/controllers/grooves/grails/mongo/PatientController.groovy
examples/grails/rdbms_mongo/grails-app/controllers/grooves/grails/mongo/ZipcodeController.groovy
examples/grails/rdbms_mongo/src/main/groovy/grooves/grails/mongo/ZipcodePatientsQuery.groovy
examples/grails/rdbms_mongo/src/main/groovy/grooves/grails/mongo/ZipcodeSummaryQuery.groovy
examples/grails/rxmongo/grails-app/controllers/rxmongo/PatientController.groovy
examples/javaee/build.gradle
examples/javaee/src/main/java/grooves/example/javaee/PatientResource.java
examples/springboot/jpa/build.gradle
examples/springboot/jpa/src/main/groovy/grooves/boot/jpa/controllers/PatientController.groovy
examples/springboot/kotlin/src/main/kotlin/grooves/boot/kotlin/controllers/PatientController.kt
examples/springboot/kotlin/src/main/kotlin/grooves/boot/kotlin/domain/PatientAccount.kt
examples/springboot/kotlin/src/main/kotlin/grooves/boot/kotlin/domain/PatientHealth.kt
grooves-api/build.gradle
grooves-api/src/main/groovy/com/github/rahulsom/grooves/api/OnSpec.java
grooves-api/src/main/groovy/com/github/rahulsom/grooves/queries/JoinSupport.java
grooves-api/src/main/groovy/com/github/rahulsom/grooves/queries/QuerySupport.java
grooves-api/src/main/groovy/com/github/rahulsom/grooves/queries/TemporalQuerySupport.java
grooves-api/src/main/groovy/com/github/rahulsom/grooves/queries/VersionedQuerySupport.java
grooves-api/src/main/groovy/com/github/rahulsom/grooves/queries/internal/Executor.java
grooves-api/src/main/groovy/com/github/rahulsom/grooves/queries/internal/JoinExecutor.java
grooves-api/src/main/groovy/com/github/rahulsom/grooves/queries/internal/QueryExecutor.java
grooves-api/src/main/groovy/com/github/rahulsom/grooves/queries/internal/SimpleExecutor.java
grooves-api/src/main/groovy/com/github/rahulsom/grooves/queries/internal/Utils.java
grooves-gorm/build.gradle
grooves-groovy/build.gradle
grooves-groovy/src/test/groovy/com/github/rahulsom/grooves/groovy/transformations/GroovesAstTransformationsSpec.groovy
grooves-java/build.gradle
grooves-types/build.gradle

This should remove rxjava1 dependencies on other projects

Make computeSnapshot method return Publisher

---

gradle/owasp-suppressions.xml
gradle/publishing.gradle
grooves-diagrams/build.gradle
grooves-site/index.html
grooves-site/styles/home.css

This will allow scanning for vulnerabilities

Enable OWASP Dependency Reports

---

examples/javaee/src/main/java/grooves/example/javaee/queries/CustomQuerySupport.java

Just check in the predicate that lastSnapshot isn't null, as for the long version.

Handle NPE in CustomQuery#getUncomputedEvents(Patient,SnapshotT,Date)

---

README.adoc
examples/grails/rdbms/build.gradle
examples/grails/rdbms/grails-app/domain/grooves/grails/rdbms/Doctor.groovy
examples/grails/rdbms/grails-app/domain/grooves/grails/rdbms/DoctorPatients.groovy
examples/grails/rdbms/grails-app/domain/grooves/grails/rdbms/Patient.groovy
examples/grails/rdbms/grails-app/domain/grooves/grails/rdbms/PatientAccount.groovy
examples/grails/rdbms/grails-app/domain/grooves/grails/rdbms/PatientHealth.groovy
examples/grails/rdbms/grails-app/domain/grooves/grails/rdbms/Zipcode.groovy
examples/grails/rdbms/grails-app/domain/grooves/grails/rdbms/ZipcodePatients.groovy
examples/grails/rdbms/grails-app/domain/grooves/grails/rdbms/ZipcodeSummary.groovy
examples/grails/rdbms/grails-app/init/grooves/example/grails/rdbms/BootStrap.groovy
examples/grails/rdbms/src/integration-test/groovy/grooves/grails/rdbms/PatientSpec.groovy
gradle.properties

This should allow for upgrading gradle and java eventually
Fixes #53

Upgrade grails to 3.3

---

gradle/jacoco.gradle

This is the version that is compatible with java 10

Upgrade jacoco to 0.8.1

---

examples/grails/rdbms/build.gradle

`mavenLocal` is a dangerous thing to depend on.

Improve repo management

---

build.gradle
examples/grails/rdbms/build.gradle
examples/javaee/build.gradle
examples/pushstyle/build.gradle
examples/springboot/jpa/build.gradle
examples/springboot/kotlin/build.gradle

This allows for easier isolation testing

Move all sonarqube reports to root project's build.gradle

---

grooves-diagrams/build.gradle
grooves-diagrams/src/main/groovy/com/github/rahulsom/grooves/asciidoctor/Aggregate.groovy
grooves-diagrams/src/main/groovy/com/github/rahulsom/grooves/asciidoctor/Event.groovy
grooves-diagrams/src/main/groovy/com/github/rahulsom/grooves/asciidoctor/SvgBuilder.groovy
grooves-diagrams/src/main/kotlin/com/github/rahulsom/grooves/asciidoctor/EventType.kt
grooves-diagrams/src/test/groovy/com/github/rahulsom/grooves/asciidoctor/SvgBuilderSpec.groovy
grooves-diagrams/src/test/resources/MergeAggregates.esdiag.svg
grooves-diagrams/src/test/resources/MergeAggregates.esdiag.txt
grooves-diagrams/src/test/resources/MergeAggregatesEffective.esdiag.svg
grooves-diagrams/src/test/resources/MergeAggregatesEffective.esdiag.txt
grooves-diagrams/src/test/resources/RevertEvent.esdiag.svg
grooves-diagrams/src/test/resources/RevertEvent.esdiag.txt
grooves-diagrams/src/test/resources/RevertEventEffective.esdiag.svg
grooves-diagrams/src/test/resources/RevertEventEffective.esdiag.txt
grooves-diagrams/src/test/resources/RevertMergeAfter.esdiag.svg
grooves-diagrams/src/test/resources/RevertMergeAfter.esdiag.txt
grooves-diagrams/src/test/resources/RevertMergeBefore.esdiag.svg
grooves-diagrams/src/test/resources/RevertMergeBefore.esdiag.txt
grooves-diagrams/src/test/resources/RevertOnRevert.esdiag.svg
grooves-diagrams/src/test/resources/RevertOnRevert.esdiag.txt
grooves-diagrams/src/test/resources/RevertOnRevertEffective.esdiag.svg
grooves-diagrams/src/test/resources/RevertOnRevertEffective.esdiag.txt
grooves-diagrams/src/test/resources/SimpleEvents.esdiag.svg
grooves-diagrams/src/test/resources/SimpleEvents.esdiag.txt

Make svg output predictable

---

grooves-diagrams/build.gradle
grooves-types/build.gradle

Revert "Update dependency org.jetbrains.dokka:dokka-gradle-plugin to v0.10.1"

---

examples/javaee/build.gradle
examples/javaee/src/main/java/grooves/example/javaee/queries/CustomQuerySupport.java
examples/pushstyle/build.gradle
examples/springboot/jpa/build.gradle
examples/springboot/kotlin/build.gradle
grooves-api/src/main/java/com/github/rahulsom/grooves/queries/TemporalQuerySupport.java
grooves-api/src/main/java/com/github/rahulsom/grooves/queries/VersionedQuerySupport.java
grooves-api/src/main/java/com/github/rahulsom/grooves/queries/internal/BaseQuery.java
grooves-docs/src/docs/asciidoc/examples/dependencies.adoc
grooves-example-test/build.gradle

compile should be considered deprecated.
It should be replaced with api and implementation

Use modern configurations with gradle

---

examples/springboot/jpa/build.gradle
grooves-api/src/main/java/com/github/rahulsom/grooves/queries/TemporalQuery.java
grooves-api/src/main/java/com/github/rahulsom/grooves/queries/TemporalQuerySupport.java
grooves-api/src/main/java/com/github/rahulsom/grooves/queries/VersionedQuery.java
grooves-api/src/main/java/com/github/rahulsom/grooves/queries/VersionedQuerySupport.java
grooves-example-test/build.gradle

`compile` is a deprecated scope

Move rxjava in grooves-example-test to implementation

---

grooves-groovy/build.gradle

testCompile and testRuntime are not going to work in gradle 7

Switch to newer scopes

---

build.gradle
examples/javaee/build.gradle
examples/pushstyle/build.gradle
examples/springboot/jpa/build.gradle
examples/springboot/kotlin/build.gradle
grooves-diagrams/build.gradle
grooves-docs/build.gradle
grooves-docs/src/docs/asciidoc/diagramming.adoc

This is better with newer gradle

Use plugins block where possible

---

examples/pushstyle/build.gradle
examples/springboot/kotlin/build.gradle
grooves-diagrams/build.gradle
grooves-types/build.gradle

This is automatically set by the plugin.

Do not set kotlin version in dependencies

---

grooves-diagrams/build.gradle

There is no more any groovy code there.

Remove groovy compilation dependency on kotlin destinationDir

---

build.gradle
grooves-core/src/main/kotlin/com/github/rahulsom/grooves/impl/GroovesQueryImpl.kt
grooves-example-pushstyle/build.gradle

chore: Bump kotlin to 1.5.x

---

build.gradle
grooves-api/build.gradle
grooves-diagrams/build.gradle
grooves-docs/src/docs/asciidoc/examples/aggregate.adoc
grooves-docs/src/docs/asciidoc/examples/baseEvent.adoc
grooves-docs/src/docs/asciidoc/examples/creationEvent.adoc
grooves-docs/src/docs/asciidoc/examples/frp.adoc
grooves-docs/src/docs/asciidoc/examples/joins.adoc
grooves-docs/src/docs/asciidoc/examples/queries.adoc
grooves-docs/src/docs/asciidoc/examples/revertEvent.adoc
grooves-docs/src/docs/asciidoc/examples/snapshot.adoc
grooves-example-javaee/build.gradle
grooves-example-pushstyle/build.gradle
grooves-example-pushstyle/src/test/kotlin/grooves/example/pushstyle/PushTest.kt
grooves-example-springboot-jpa/build.gradle
grooves-example-springboot-kotlin/build.gradle
grooves-example-test/build.gradle
grooves-groovy/build.gradle
grooves-types/build.gradle

Also use junit platform for running tests

chore: Upgrade groovy to 3.x and Spock to 2.1

---

grooves-docs/build.gradle

This change replaces jitpack with a proper repo for the block switch.

refactor: Remove jitpack

---

grooves-docs/build.gradle.kts

Revert "chore(deps): update plugin org.ajoberstar.git-publish to v4"

---

gradle/libs.versions.toml

Groovy goes from 3.0.14 to 4.0.6.
Spock goes from 2.1-groovy-3.0 to 2.3-groovy-4.0.

chore(deps): Update groovy and spock

---

grooves-example-pushstyle/src/main/kotlin/grooves/example/push/Transaction.kt

Leaving it in the body forces defining them.

refactor: Remove getter/setter for revertedBy

---

settings.gradle.kts

chore(gradle): Move config from gradleEnterprise to develocity

---

gradle.properties
gradle/wrapper/gradle-wrapper.properties
grooves-diagrams/build.gradle.kts
grooves-docs/build.gradle.kts

Also, enable parallel builds and fix buildDir warnings

chore: Upgrade to gradle 8.12

---

gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties

- **chore: Upgrade to gradle 8.12**
- **chore; Upgrade to gradle 8.14.3**

upgrade gradle and waena

---

.github/workflows/build.yml
grooves-api/build.gradle.kts
grooves-example-javaee/build.gradle.kts
grooves-example-test/build.gradle.kts
grooves-groovy/build.gradle.kts
grooves-java/build.gradle.kts

This keeps generated classes at JDK 17.

chore: Upgrade Build to JDK 21

---

gradle/libs.versions.toml
grooves-example-javaee/build.gradle.kts
grooves-example-springboot-kotlin/build.gradle.kts
grooves-example-test/build.gradle.kts
grooves-example-test/src/main/java/com/github/rahulsom/grooves/test/HttpResponseDecorator.java

- **chore: Drop groovy plugin from examples that don't need it**
- **chore: Replace groovy-json and groovy-xml with jackson**

replace spock
